#pragma once
#define SERIAL
#define MASTER_LEFT
#define SPLIT_USB_DETECT
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE

// #undef DIODE_DIRECTION
// #define DIODE_DIRECTION ROW2COL

#undef WS2812_DI_PIN
#define WS2812_DI_PIN F5
#undef RGBLIGHT_LED_COUNT
#define RGBLIGHT_LED_COUNT 32
#define RGBLED_SPLIT { 16, 16 }
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL

#define ENCODER_A_PINS { D3 }
#define ENCODER_B_PINS { D2 }
