#pragma once
#define SERIAL
#define MASTER_LEFT
#undef DIODE_DIRECTION
#define DIODE_DIRECTION ROW2COL
#undef WS2812_DI_PIN
#define WS2812_DI_PIN B7
#undef RGBLIGHT_LED_COUNT
#define RGBLIGHT_LED_COUNT 52
#define RGBLED_SPLIT { 26, 26 }
#define RGBLIGHT_DEFAULT_HUE 85
#define RGBLIGHT_DEFAULT_VAL 125
#undef RGBLIGHT_DEFAULT_MODE
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_BREATHING
